import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const colleges = [
  // IITs
  {
    name: 'IIT Madras',
    location: 'Chennai, Tamil Nadu',
    city: 'Chennai',
    state: 'Tamil Nadu',
    fees: 215000,
    rating: 4.9,
    established: 1959,
    type: 'Public',
    affiliation: 'Autonomous',
    totalStudents: 9000,
    description: 'Number one ranked engineering college in India, known for research excellence and innovation.',
    nirf: 1,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/6/69/IIT_Madras_Logo.svg',
  },
  {
    name: 'IIT Delhi',
    location: 'New Delhi, Delhi',
    city: 'New Delhi',
    state: 'Delhi',
    fees: 210000,
    rating: 4.8,
    established: 1961,
    type: 'Public',
    affiliation: 'Autonomous',
    totalStudents: 8500,
    description: 'Top ranked technical university in the capital, premier destination for engineers and researchers.',
    nirf: 2,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/f/fd/Indian_Institute_of_Technology_Delhi_Logo.svg',
  },
  {
    name: 'IIT Bombay',
    location: 'Mumbai, Maharashtra',
    city: 'Mumbai',
    state: 'Maharashtra',
    fees: 220000,
    rating: 4.8,
    established: 1958,
    type: 'Public',
    affiliation: 'Autonomous',
    totalStudents: 10000,
    description: 'Premier engineering institute in India located in the financial capital, known for entrepreneurship.',
    nirf: 3,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/4/47/IIT_Bombay_Logo.svg',
  },
  {
    name: 'IIT Kanpur',
    location: 'Kanpur, Uttar Pradesh',
    city: 'Kanpur',
    state: 'Uttar Pradesh',
    fees: 212000,
    rating: 4.7,
    established: 1959,
    type: 'Public',
    affiliation: 'Autonomous',
    totalStudents: 8000,
    description: 'Top IIT for research and innovation, strong in sciences, engineering and computer science.',
    nirf: 4,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/b/bd/Indian_Institute_of_Technology_Kanpur_Logo.svg',
  },
  {
    name: 'IIT Kharagpur',
    location: 'Kharagpur, West Bengal',
    city: 'Kharagpur',
    state: 'West Bengal',
    fees: 200000,
    rating: 4.7,
    established: 1951,
    type: 'Public',
    affiliation: 'Autonomous',
    totalStudents: 12000,
    description: 'Oldest and largest IIT, pioneer in technical education in India with the largest campus.',
    nirf: 5,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/1/1c/IIT_Kharagpur_Logo.svg',
  },
  {
    name: 'IIT Roorkee',
    location: 'Roorkee, Uttarakhand',
    city: 'Roorkee',
    state: 'Uttarakhand',
    fees: 205000,
    rating: 4.6,
    established: 1847,
    type: 'Public',
    affiliation: 'Autonomous',
    totalStudents: 9500,
    description: 'Oldest technical institute in Asia with outstanding civil engineering and research heritage.',
    nirf: 6,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/5/59/IIT_Roorkee_logo.svg',
  },
  {
    name: 'IIT Guwahati',
    location: 'Guwahati, Assam',
    city: 'Guwahati',
    state: 'Assam',
    fees: 208000,
    rating: 4.5,
    established: 1994,
    type: 'Public',
    affiliation: 'Autonomous',
    totalStudents: 5500,
    description: 'Premier IIT in northeast India with beautiful campus on the banks of river Brahmaputra.',
    nirf: 7,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/1/12/IIT_Guwahati_Logo.svg',
  },
  {
    name: 'IIT Hyderabad',
    location: 'Hyderabad, Telangana',
    city: 'Hyderabad',
    state: 'Telangana',
    fees: 208000,
    rating: 4.4,
    established: 2008,
    type: 'Public',
    affiliation: 'Autonomous',
    totalStudents: 3500,
    description: 'New generation IIT with strong research focus and innovation culture in AI and data science.',
    nirf: 14,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/0/09/IIT_Hyderabad_logo.svg',
  },
  {
    name: 'IIT Indore',
    location: 'Indore, Madhya Pradesh',
    city: 'Indore',
    state: 'Madhya Pradesh',
    fees: 206000,
    rating: 4.3,
    established: 2009,
    type: 'Public',
    affiliation: 'Autonomous',
    totalStudents: 2800,
    description: 'Fast growing IIT in central India known for research output and excellent faculty.',
    nirf: 17,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/f/f8/IIT_Indore_Logo.png',
  },
  {
    name: 'IIT Bhubaneswar',
    location: 'Bhubaneswar, Odisha',
    city: 'Bhubaneswar',
    state: 'Odisha',
    fees: 204000,
    rating: 4.2,
    established: 2008,
    type: 'Public',
    affiliation: 'Autonomous',
    totalStudents: 2500,
    description: 'IIT in eastern India with strong programs in engineering and sciences.',
    nirf: 22,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/d/d5/IIT_Bhubaneswar_logo.png',
  },
  {
    name: 'IIT Gandhinagar',
    location: 'Gandhinagar, Gujarat',
    city: 'Gandhinagar',
    state: 'Gujarat',
    fees: 207000,
    rating: 4.3,
    established: 2008,
    type: 'Public',
    affiliation: 'Autonomous',
    totalStudents: 2200,
    description: 'Innovative IIT known for its liberal arts integrated engineering curriculum.',
    nirf: 16,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/b/b5/IIT_Gandhinagar_Logo.png',
  },
  {
    name: 'IIT Patna',
    location: 'Patna, Bihar',
    city: 'Patna',
    state: 'Bihar',
    fees: 203000,
    rating: 4.1,
    established: 2008,
    type: 'Public',
    affiliation: 'Autonomous',
    totalStudents: 2000,
    description: 'IIT in Bihar offering quality technical education with focus on research and development.',
    nirf: 28,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/a/a0/IIT_Patna_logo.png',
  },
  {
    name: 'IIT Mandi',
    location: 'Mandi, Himachal Pradesh',
    city: 'Mandi',
    state: 'Himachal Pradesh',
    fees: 202000,
    rating: 4.1,
    established: 2009,
    type: 'Public',
    affiliation: 'Autonomous',
    totalStudents: 1800,
    description: 'IIT in the Himalayas known for its unique research in sustainability and mountain ecosystems.',
    nirf: 32,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/d/d5/IIT_Mandi_logo.png',
  },
  {
    name: 'IIT Jodhpur',
    location: 'Jodhpur, Rajasthan',
    city: 'Jodhpur',
    state: 'Rajasthan',
    fees: 205000,
    rating: 4.2,
    established: 2008,
    type: 'Public',
    affiliation: 'Autonomous',
    totalStudents: 2100,
    description: 'IIT in the blue city of Rajasthan with strong focus on AI, renewable energy and design.',
    nirf: 25,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/c/c6/IIT_Jodhpur_Logo.png',
  },
  {
    name: 'IIT Ropar',
    location: 'Rupnagar, Punjab',
    city: 'Rupnagar',
    state: 'Punjab',
    fees: 203000,
    rating: 4.1,
    established: 2008,
    type: 'Public',
    affiliation: 'Autonomous',
    totalStudents: 1900,
    description: 'IIT in Punjab with strong emphasis on research and industry collaboration.',
    nirf: 30,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/e/e4/IIT_Ropar_logo.png',
  },
  {
    name: 'IIT Varanasi (BHU)',
    location: 'Varanasi, Uttar Pradesh',
    city: 'Varanasi',
    state: 'Uttar Pradesh',
    fees: 198000,
    rating: 4.3,
    established: 1919,
    type: 'Public',
    affiliation: 'Autonomous',
    totalStudents: 6500,
    description: 'One of oldest technical institutions in India, part of Banaras Hindu University campus.',
    nirf: 10,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/b/b8/IIT_BHU_logo.png',
  },
  {
    name: 'IIT Dhanbad (ISM)',
    location: 'Dhanbad, Jharkhand',
    city: 'Dhanbad',
    state: 'Jharkhand',
    fees: 196000,
    rating: 4.2,
    established: 1926,
    type: 'Public',
    affiliation: 'Autonomous',
    totalStudents: 7000,
    description: 'Premier institute for mining and mineral engineering, now an IIT with diverse programs.',
    nirf: 12,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/f/f1/IIT_ISM_logo.png',
  },

  // NITs
  {
    name: 'NIT Trichy',
    location: 'Tiruchirappalli, Tamil Nadu',
    city: 'Tiruchirappalli',
    state: 'Tamil Nadu',
    fees: 130000,
    rating: 4.3,
    established: 1964,
    type: 'Public',
    affiliation: 'NIT',
    totalStudents: 6000,
    description: 'Top NIT in India with excellent placements, strong alumni network and research culture.',
    nirf: 8,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/5/5e/NIT_Trichy_Logo.svg',
  },
  {
    name: 'NIT Surathkal',
    location: 'Mangalore, Karnataka',
    city: 'Mangalore',
    state: 'Karnataka',
    fees: 125000,
    rating: 4.2,
    established: 1960,
    type: 'Public',
    affiliation: 'NIT',
    totalStudents: 5500,
    description: 'Reputed NIT in Karnataka known for technical programs and excellent placement record.',
    nirf: 15,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/f/fd/NITK_Logo.png',
  },
  {
    name: 'NIT Warangal',
    location: 'Warangal, Telangana',
    city: 'Warangal',
    state: 'Telangana',
    fees: 128000,
    rating: 4.2,
    established: 1959,
    type: 'Public',
    affiliation: 'NIT',
    totalStudents: 5800,
    description: 'Premier NIT in Telangana with strong industry collaborations and placement record.',
    nirf: 18,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/4/4b/NIT_Warangal_Logo.png',
  },
  {
    name: 'NIT Calicut',
    location: 'Kozhikode, Kerala',
    city: 'Kozhikode',
    state: 'Kerala',
    fees: 122000,
    rating: 4.1,
    established: 1961,
    type: 'Public',
    affiliation: 'NIT',
    totalStudents: 5200,
    description: 'Top NIT in Kerala with strong technical programs and beautiful campus in the western ghats.',
    nirf: 20,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/8/85/NIT_Calicut_Logo.png',
  },
  {
    name: 'NIT Rourkela',
    location: 'Rourkela, Odisha',
    city: 'Rourkela',
    state: 'Odisha',
    fees: 120000,
    rating: 4.1,
    established: 1961,
    type: 'Public',
    affiliation: 'NIT',
    totalStudents: 5000,
    description: 'Leading NIT in eastern India with strong programs in metallurgy and mechanical engineering.',
    nirf: 19,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/8/84/NIT_Rourkela_colour_logo.png',
  },
  {
    name: 'NIT Allahabad (MNNIT)',
    location: 'Prayagraj, Uttar Pradesh',
    city: 'Prayagraj',
    state: 'Uttar Pradesh',
    fees: 118000,
    rating: 4.0,
    established: 1961,
    type: 'Public',
    affiliation: 'NIT',
    totalStudents: 4800,
    description: 'Motilal Nehru NIT, one of the oldest NITs in India located in the city of Prayagraj.',
    nirf: 24,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/b/b2/Mnnit_logo.png',
  },
  {
    name: 'NIT Jaipur (MNIT)',
    location: 'Jaipur, Rajasthan',
    city: 'Jaipur',
    state: 'Rajasthan',
    fees: 119000,
    rating: 4.0,
    established: 1963,
    type: 'Public',
    affiliation: 'NIT',
    totalStudents: 4600,
    description: 'Malaviya NIT in the pink city of Jaipur with strong technical programs and placements.',
    nirf: 26,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/8/8e/Mnit_logo.jpg',
  },
  {
    name: 'NIT Nagpur (VNIT)',
    location: 'Nagpur, Maharashtra',
    city: 'Nagpur',
    state: 'Maharashtra',
    fees: 117000,
    rating: 4.0,
    established: 1960,
    type: 'Public',
    affiliation: 'NIT',
    totalStudents: 4700,
    description: 'Visvesvaraya NIT in central India with excellent technical programs and industry connections.',
    nirf: 27,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/5/54/VNIT_logo.png',
  },
  {
    name: 'NIT Kurukshetra',
    location: 'Kurukshetra, Haryana',
    city: 'Kurukshetra',
    state: 'Haryana',
    fees: 116000,
    rating: 3.9,
    established: 1963,
    type: 'Public',
    affiliation: 'NIT',
    totalStudents: 4500,
    description: 'NIT in the historical city of Kurukshetra with strong engineering and technology programs.',
    nirf: 29,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/b/b8/NIT_Kurukshetra_logo.png',
  },
  {
    name: 'NIT Durgapur',
    location: 'Durgapur, West Bengal',
    city: 'Durgapur',
    state: 'West Bengal',
    fees: 115000,
    rating: 3.9,
    established: 1960,
    type: 'Public',
    affiliation: 'NIT',
    totalStudents: 4400,
    description: 'NIT in West Bengal with strong programs in metallurgy, chemical and mechanical engineering.',
    nirf: 31,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/8/8a/NIT_Durgapur_Logo.png',
  },
  {
    name: 'NIT Silchar',
    location: 'Silchar, Assam',
    city: 'Silchar',
    state: 'Assam',
    fees: 112000,
    rating: 3.8,
    established: 1967,
    type: 'Public',
    affiliation: 'NIT',
    totalStudents: 4000,
    description: 'NIT in northeast India serving students from the region with quality technical education.',
    nirf: 38,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/a/a4/NIT_Silchar_Logo.png',
  },
  {
    name: 'NIT Srinagar',
    location: 'Srinagar, Jammu & Kashmir',
    city: 'Srinagar',
    state: 'Jammu & Kashmir',
    fees: 110000,
    rating: 3.7,
    established: 1960,
    type: 'Public',
    affiliation: 'NIT',
    totalStudents: 3800,
    description: 'NIT in the beautiful Kashmir valley offering technical education in a scenic environment.',
    nirf: 45,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/f/f4/NIT_Srinagar_logo.png',
  },
  {
    name: 'NIT Bhopal (MANIT)',
    location: 'Bhopal, Madhya Pradesh',
    city: 'Bhopal',
    state: 'Madhya Pradesh',
    fees: 114000,
    rating: 3.9,
    established: 1960,
    type: 'Public',
    affiliation: 'NIT',
    totalStudents: 4200,
    description: 'Maulana Azad NIT in the capital of Madhya Pradesh with diverse engineering programs.',
    nirf: 33,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/7/7b/MANIT_Bhopal_logo.png',
  },
  {
    name: 'NIT Patna',
    location: 'Patna, Bihar',
    city: 'Patna',
    state: 'Bihar',
    fees: 111000,
    rating: 3.8,
    established: 1886,
    type: 'Public',
    affiliation: 'NIT',
    totalStudents: 3600,
    description: 'One of the oldest technical institutes in Asia, now a NIT serving students from Bihar and beyond.',
    nirf: 40,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/2/2e/NIT_Patna_logo.png',
  },
  {
    name: 'NIT Hamirpur',
    location: 'Hamirpur, Himachal Pradesh',
    city: 'Hamirpur',
    state: 'Himachal Pradesh',
    fees: 110000,
    rating: 3.8,
    established: 1986,
    type: 'Public',
    affiliation: 'NIT',
    totalStudents: 3500,
    description: 'NIT in Himachal Pradesh with scenic campus and strong technical programs.',
    nirf: 42,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/b/b7/NIT_Hamirpur_logo.png',
  },

  // IIITs and Other Top Colleges
  {
    name: 'IIIT Hyderabad',
    location: 'Hyderabad, Telangana',
    city: 'Hyderabad',
    state: 'Telangana',
    fees: 580000,
    rating: 4.5,
    established: 1998,
    type: 'Public',
    affiliation: 'Autonomous',
    totalStudents: 2500,
    description: 'Premier institute for IT and AI research in India with outstanding placement record.',
    nirf: 23,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/b/b4/IIIT_Hyderabad_Logo.svg',
  },
  {
    name: 'BITS Pilani',
    location: 'Pilani, Rajasthan',
    city: 'Pilani',
    state: 'Rajasthan',
    fees: 480000,
    rating: 4.6,
    established: 1964,
    type: 'Private',
    affiliation: 'Deemed University',
    totalStudents: 7000,
    description: 'Top private engineering institute known for its unique academic system and work integrated learning.',
    nirf: 26,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/d/d3/BITS_Pilani-Logo.svg',
  },
  {
    name: 'VIT Vellore',
    location: 'Vellore, Tamil Nadu',
    city: 'Vellore',
    state: 'Tamil Nadu',
    fees: 350000,
    rating: 4.1,
    established: 1984,
    type: 'Private',
    affiliation: 'Deemed University',
    totalStudents: 35000,
    description: 'Largest private engineering college with strong industry connections and global exposure.',
    nirf: 11,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/b/b6/VIT_University_seal_2017.svg',
  },
  {
    name: 'DTU Delhi',
    location: 'New Delhi, Delhi',
    city: 'New Delhi',
    state: 'Delhi',
    fees: 175000,
    rating: 4.0,
    established: 1941,
    type: 'Public',
    affiliation: 'State University',
    totalStudents: 8000,
    description: 'Top state engineering university in Delhi with excellent placements in top tech companies.',
    nirf: 36,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/b/b0/DTU%2C_Delhi_official_logo.png',
  },
  {
    name: 'Jadavpur University',
    location: 'Kolkata, West Bengal',
    city: 'Kolkata',
    state: 'West Bengal',
    fees: 80000,
    rating: 4.2,
    established: 1955,
    type: 'Public',
    affiliation: 'State University',
    totalStudents: 15000,
    description: 'Top state university in eastern India with strong research culture and affordable education.',
    nirf: 9,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/4/4b/Jadavpur_University_Logo.svg',
  },
  {
    name: 'Manipal Institute of Technology',
    location: 'Manipal, Karnataka',
    city: 'Manipal',
    state: 'Karnataka',
    fees: 420000,
    rating: 4.0,
    established: 1957,
    type: 'Private',
    affiliation: 'Deemed University',
    totalStudents: 15000,
    description: 'Top private university in South India with multinational exposure and strong alumni network.',
    nirf: 47,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/8/85/Manipal_Academy_of_Higher_Education_logo.png',
  },
  {
    name: 'SRM Institute of Science and Technology',
    location: 'Chennai, Tamil Nadu',
    city: 'Chennai',
    state: 'Tamil Nadu',
    fees: 380000,
    rating: 3.9,
    established: 1985,
    type: 'Private',
    affiliation: 'Deemed University',
    totalStudents: 52000,
    description: 'One of the largest private universities with strong placement record and research facilities.',
    nirf: 30,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/f/f9/SRM_Institute_of_Science_and_Technology_Logo.png',
  },
  {
    name: 'Thapar Institute of Engineering',
    location: 'Patiala, Punjab',
    city: 'Patiala',
    state: 'Punjab',
    fees: 360000,
    rating: 4.1,
    established: 1956,
    type: 'Private',
    affiliation: 'Deemed University',
    totalStudents: 10000,
    description: 'Top ranked private university in North India with excellent placements and research output.',
    nirf: 27,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/b/b5/Thapar_University_logo.png',
  },
];

const courseTemplates = [
  { name: 'B.Tech Computer Science', duration: '4 years', seats: 60 },
  { name: 'B.Tech Electronics & Communication', duration: '4 years', seats: 60 },
  { name: 'B.Tech Mechanical Engineering', duration: '4 years', seats: 60 },
  { name: 'B.Tech Civil Engineering', duration: '4 years', seats: 60 },
  { name: 'B.Tech Electrical Engineering', duration: '4 years', seats: 60 },
];

const examMap: Record<string, string> = {
  'IIT': 'JEE Advanced',
  'NIT': 'JEE Main',
  'IIIT': 'JEE Main',
  'BITS': 'BITSAT',
  'VIT': 'VITEEE',
  'DTU': 'JEE Main',
  'Jadavpur': 'WBJEE',
  'Manipal': 'MET',
  'SRM': 'SRMJEEE',
  'Thapar': 'JEE Main',
};

function getExam(collegeName: string): string {
  for (const key of Object.keys(examMap)) {
    if (collegeName.includes(key)) return examMap[key];
  }
  return 'JEE Main';
}

async function main() {
  console.log('Clearing existing data...');
  await prisma.answer.deleteMany();
  await prisma.question.deleteMany();
  await prisma.savedCollege.deleteMany();
  await prisma.review.deleteMany();
  await prisma.placement.deleteMany();
  await prisma.course.deleteMany();
  await prisma.college.deleteMany();

  console.log('Seeding colleges...');

  for (let i = 0; i < colleges.length; i++) {
    const c = colleges[i];
    const college = await prisma.college.create({ data: c });
    const primaryExam = getExam(c.name);

    // Create 5 courses
    for (let j = 0; j < courseTemplates.length; j++) {
      const baseRank = (i + 1) * 600 + j * 200;
      await prisma.course.create({
        data: {
          name: courseTemplates[j].name,
          duration: courseTemplates[j].duration,
          fees: c.fees + j * 8000,
          seats: courseTemplates[j].seats,
          exam: primaryExam,
          minRank: baseRank,
          maxRank: baseRank + 5000,
          collegeId: college.id,
        },
      });
    }

    // Create placement records for 3 years
    for (let y = 2022; y <= 2024; y++) {
      await prisma.placement.create({
        data: {
          year: y,
          avgPackage:
            Math.round(
              (8 + (colleges.length - i) * 0.5 + (y - 2022) * 0.4) * 10
            ) / 10,
          maxPackage:
            Math.round((30 + (colleges.length - i) * 0.8) * 10) / 10,
          placementPct:
            Math.round((65 + (colleges.length - i) * 0.7) * 10) / 10,
          topRecruiters:
            'Google, Microsoft, Amazon, Flipkart, Infosys, TCS, Wipro, Deloitte',
          collegeId: college.id,
        },
      });
    }

    // Create reviews
    await prisma.review.createMany({
      data: [
        {
          rating: 4.5,
          title: 'Great experience overall',
          body: 'The faculty is excellent and campus life is vibrant. Placement opportunities are outstanding. Highly recommended for aspiring engineers.',
          author: 'Alumni 2022',
          collegeId: college.id,
        },
        {
          rating: 4.0,
          title: 'Good placements but high competition',
          body: 'Placement record is strong but you need to work very hard. Infrastructure is world class. The peer group is very competitive and motivating.',
          author: 'Student 2023',
          collegeId: college.id,
        },
        {
          rating: 4.2,
          title: 'Excellent research opportunities',
          body: 'If you are into research, this is the place to be. Labs are well equipped and professors are very supportive of student projects and publications.',
          author: 'Research Scholar 2021',
          collegeId: college.id,
        },
      ],
    });

    console.log(`✓ ${i + 1}. ${c.name}`);
  }

  console.log(`\n✅ Done! Seeded ${colleges.length} colleges successfully.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });